use u_jastrzab
go
  exec dbo.AddPerson "Robert","Nowakowski",1,null
  exec dbo.AddPerson "Kacper","Nowakowski",1,null
  exec dbo.AddPerson "W³adys³aw","Kowalski",0,71
  exec dbo.AddPerson "Aberald","Kowalski",0,28
  exec dbo.AddPerson "Kacper","Kosowski",0,62
  exec dbo.AddPerson "Kacper","B³aszczykowski",0,null
  exec dbo.AddPerson "Mateusz","Lewandowski",0,27
  exec dbo.AddPerson "Kamil","Jankowski",1,null
  exec dbo.AddPerson "Krzysztof","Knapik",1,11
  exec dbo.AddPerson "Kacper","Huszczak",1,62
  exec dbo.AddPerson "Mateusz","Kosowski",0,null
  exec dbo.AddPerson "W³adys³aw","Dudek",1,null
  exec dbo.AddPerson "Jan","Kowalski",0,6
  exec dbo.AddPerson "Mateusz","Filipowski",0,null
  exec dbo.AddPerson "Ryszard","Filipowski",0,null
  exec dbo.AddPerson "Micha³","Knapik",1,36
  exec dbo.AddPerson "Bartosz","Goleñ",1,null
  exec dbo.AddPerson "Stanis³aw","Piszczek",0,null
  exec dbo.AddPerson "Krzysztof","B³aszczykowski",0,77
  exec dbo.AddPerson "Leszek","Nowak",0,18
  exec dbo.AddPerson "Robert","Goleñ",0,null
  exec dbo.AddPerson "Jerzy","Dudek",0,85
  exec dbo.AddPerson "Kamil","Zaporowski",0,10
  exec dbo.AddPerson "W³adys³aw","Witek",1,24
  exec dbo.AddPerson "Marek","Jankowski",1,8
  exec dbo.AddPerson "Pawe³","Zaporowski",0,12
  exec dbo.AddPerson "Marek","Lewandowski",0,null
  exec dbo.AddPerson "Micha³","Goleñ",1,null
  exec dbo.AddPerson "Krzysztof","Dudek",0,null
  exec dbo.AddPerson "Bartosz","Boruc",0,25
  exec dbo.AddPerson "Robert","Frankowski",1,null
  exec dbo.AddPerson "Robert","Witek",0,null
  exec dbo.AddPerson "Jerzy","Jankowski",1,null
  exec dbo.AddPerson "W³adys³aw","B³aszczykowski",1,null
  exec dbo.AddPerson "Kamil","Zaporowski",1,null
  exec dbo.AddPerson "Jerzy","Kowalski",0,82
  exec dbo.AddPerson "Krzysztof","Frankowski",1,null
  exec dbo.AddPerson "Robert","Boruc",1,15
  exec dbo.AddPerson "Bartosz","B³aszczykowski",0,null
  exec dbo.AddPerson "Pawe³","Zaporowski",1,null
  exec dbo.AddPerson "W³adys³aw","Kowalski",0,92
  exec dbo.AddPerson "Stanis³aw","Dudek",0,null
  exec dbo.AddPerson "Stanis³aw","Frankowski",1,null
  exec dbo.AddPerson "W³adys³aw","Piszczek",0,20
  exec dbo.AddPerson "Leszek","Boruc",1,99
  exec dbo.AddPerson "Kacper","Lewandowski",1,47
  exec dbo.AddPerson "Ryszard","Lewandowski",0,null
  exec dbo.AddPerson "Pawe³","B³aszczykowski",0,null
  exec dbo.AddPerson "Aberald","Frankowski",0,null
  exec dbo.AddPerson "Ryszard","Kosowski",0,null
  exec dbo.AddPerson "Jerzy","Nowakowski",0,60
  exec dbo.AddPerson "Mateusz","Giza",1,null
  exec dbo.AddPerson "Jerzy","Huszczak",1,49
  exec dbo.AddPerson "Micha³","Nowak",1,null
  exec dbo.AddPerson "Micha³","Wójcik",0,37
  exec dbo.AddPerson "Micha³","Zaporowski",1,99
  exec dbo.AddPerson "Józef","Kowalski",1,null
  exec dbo.AddPerson "Piotr","Giza",0,null
  exec dbo.AddPerson "W³adys³aw","Goleñ",1,null
  exec dbo.AddPerson "Jerzy","Knapik",0,53
  exec dbo.AddPerson "Adam","Goleñ",1,41
  exec dbo.AddPerson "Leszek","Jankowski",1,80
  exec dbo.AddPerson "Adam","Nowak",0,25
  exec dbo.AddPerson "Marek","Knapik",1,null
  exec dbo.AddPerson "Pawe³","Kowalski",1,null
  exec dbo.AddPerson "Zbigniew","Witek",0,null
  exec dbo.AddPerson "Krzysztof","Kosowski",1,37
  exec dbo.AddPerson "Mateusz","Goleñ",0,46
  exec dbo.AddPerson "Aberald","Giza",1,null
  exec dbo.AddPerson "Pawe³","Nowak",0,20
  exec dbo.AddPerson "Józef","Giza",0,null
  exec dbo.AddPerson "Bartosz","Boruc",0,58
  exec dbo.AddPerson "W³adys³aw","Zaporowski",1,null
  exec dbo.AddPerson "Kacper","Piszczek",0,null
  exec dbo.AddPerson "Leszek","Goleñ",1,null
  exec dbo.AddPerson "Ryszard","Wójcik",1,47
  exec dbo.AddPerson "Pawe³","Dudek",0,53
  exec dbo.AddPerson "W³adys³aw","Frankowski",1,79
  exec dbo.AddPerson "Aberald","Karasiñski",1,null
  exec dbo.AddPerson "Ryszard","Goleñ",1,null
  exec dbo.AddPerson "Krzysztof","Knapik",1,89
  exec dbo.AddPerson "Marek","Nowak",0,30
  exec dbo.AddPerson "Kacper","Goleñ",1,97
  exec dbo.AddPerson "Piotr","Frankowski",1,71
  exec dbo.AddPerson "Pawe³","Lewandowski",0,null
  exec dbo.AddPerson "Mateusz","Piszczek",1,null
  exec dbo.AddPerson "Jerzy","Witek",1,1
  exec dbo.AddPerson "Ryszard","Wójcik",0,66
  exec dbo.AddPerson "Micha³","Filipowski",0,48
  exec dbo.AddPerson "W³adys³aw","Boruc",1,70
  exec dbo.AddPerson "Ryszard","Karasiñski",1,null
  exec dbo.AddPerson "Józef","Frankowski",0,94
  exec dbo.AddPerson "Józef","Huszczak",0,92
  exec dbo.AddPerson "Leszek","Nowakowski",1,null
  exec dbo.AddPerson "Stanis³aw","Filipowski",1,null
  exec dbo.AddPerson "Bartosz","Giza",1,50
  exec dbo.AddPerson "Krzysztof","Knapik",0,67
  exec dbo.AddPerson "Józef","Boruc",1,null
  exec dbo.AddPerson "Stanis³aw","Nowakowski",0,54
  exec dbo.AddPerson "Krzysztof","Nowak",0,null
  exec dbo.AddPerson "Krzysztof","Huszczak",1,95
  exec dbo.AddPerson "Adam","B³aszczykowski",1,null
  exec dbo.AddPerson "W³adys³aw","Dudek",1,null
  exec dbo.AddPerson "Zbigniew","Wójcik",0,89
  exec dbo.AddPerson "Kacper","Knapik",1,29
  exec dbo.AddPerson "Kacper","Huszczak",1,61
  exec dbo.AddPerson "Marek","Lewandowski",1,null
  exec dbo.AddPerson "Micha³","Kowalski",0,22
  exec dbo.AddPerson "Aberald","Goleñ",1,null
  exec dbo.AddPerson "Zbigniew","Piszczek",1,1
  exec dbo.AddPerson "Aberald","Goleñ",0,54
  exec dbo.AddPerson "Pawe³","Filipowski",1,null
  exec dbo.AddPerson "Adam","Kowalski",1,82
  exec dbo.AddPerson "Ryszard","Nowakowski",1,9
  exec dbo.AddPerson "Piotr","Boruc",0,null
  exec dbo.AddPerson "W³adys³aw","Knapik",0,100
  exec dbo.AddPerson "Bartosz","Filipowski",1,null
  exec dbo.AddPerson "W³adys³aw","Wójcik",1,null
  exec dbo.AddPerson "Kacper","Witek",0,58
  exec dbo.AddPerson "Józef","Piszczek",1,59
  exec dbo.AddPerson "Mateusz","Giza",1,80
  exec dbo.AddPerson "Jan","Piszczek",1,37
  exec dbo.AddPerson "Stanis³aw","Kowalski",0,83
  exec dbo.AddPerson "Jan","Jankowski",0,null
  exec dbo.AddPerson "Bartosz","Nowakowski",0,17
  exec dbo.AddPerson "Kacper","Lewandowski",1,null
  exec dbo.AddPerson "Kacper","Nowak",1,67
  exec dbo.AddPerson "Krzysztof","Zaporowski",0,86
  exec dbo.AddPerson "Pawe³","Kosowski",0,null
  exec dbo.AddPerson "Robert","Kosowski",0,46
  exec dbo.AddPerson "Leszek","Filipowski",1,14
  exec dbo.AddPerson "Pawe³","Dudek",1,79
  exec dbo.AddPerson "Bartosz","Kosowski",0,null
  exec dbo.AddPerson "Robert","Witek",0,null
  exec dbo.AddPerson "Zbigniew","Wójcik",0,62
  exec dbo.AddPerson "Kacper","Filipowski",1,null
  exec dbo.AddPerson "Zbigniew","Boruc",0,59
  exec dbo.AddPerson "Robert","Karasiñski",0,null
  exec dbo.AddPerson "Ryszard","Zaporowski",0,null
  exec dbo.AddPerson "Józef","Karasiñski",0,41
  exec dbo.AddPerson "Stanis³aw","Huszczak",0,40
  exec dbo.AddPerson "Kacper","Zaporowski",1,null
  exec dbo.AddPerson "Jan","Giza",1,4
  exec dbo.AddPerson "Stanis³aw","Kowalski",0,null
  exec dbo.AddPerson "Kacper","Kosowski",1,15
  exec dbo.AddPerson "Jerzy","Goleñ",0,null
  exec dbo.AddPerson "Adam","Jankowski",1,50
  exec dbo.AddPerson "Aberald","Piszczek",1,null
  exec dbo.AddPerson "Marek","Knapik",1,39
  exec dbo.AddPerson "Adam","Knapik",1,null
  exec dbo.AddPerson "Marek","Knapik",0,60
  exec dbo.AddPerson "W³adys³aw","Filipowski",0,75
  exec dbo.AddPerson "Kacper","Karasiñski",1,null
  exec dbo.AddPerson "Piotr","Piszczek",0,null
  exec dbo.AddPerson "Józef","Huszczak",0,null
  exec dbo.AddPerson "Jerzy","Knapik",1,62
  exec dbo.AddPerson "Adam","Lewandowski",0,null
  exec dbo.AddPerson "Marek","Huszczak",1,24
  exec dbo.AddPerson "Robert","Wójcik",1,null
  exec dbo.AddPerson "Kacper","Wójcik",1,null
  exec dbo.AddPerson "Marek","Lewandowski",0,null
  exec dbo.AddPerson "Ryszard","Frankowski",0,58
  exec dbo.AddPerson "Zbigniew","Piszczek",1,null
  exec dbo.AddPerson "Ryszard","Kosowski",1,28
  exec dbo.AddPerson "Jerzy","Goleñ",0,76
  exec dbo.AddPerson "Aberald","Nowakowski",0,10
  exec dbo.AddPerson "W³adys³aw","Karasiñski",0,null
  exec dbo.AddPerson "Robert","B³aszczykowski",0,null
  exec dbo.AddPerson "Zbigniew","Karasiñski",1,null
  exec dbo.AddPerson "Aberald","Goleñ",0,35
  exec dbo.AddPerson "Ryszard","Jankowski",0,null
  exec dbo.AddPerson "Zbigniew","Kowalski",0,null
  exec dbo.AddPerson "Marek","Wójcik",0,42
  exec dbo.AddPerson "Zbigniew","Nowak",0,44
  exec dbo.AddPerson "Pawe³","Lewandowski",0,null
  exec dbo.AddPerson "Adam","Nowak",0,null
  exec dbo.AddPerson "Józef","Filipowski",1,null
  exec dbo.AddPerson "Mateusz","Jankowski",1,null
  exec dbo.AddPerson "W³adys³aw","Kowalski",0,94
  exec dbo.AddPerson "Aberald","B³aszczykowski",0,33
  exec dbo.AddPerson "Zbigniew","Kowalski",1,null
  exec dbo.AddPerson "Aberald","Huszczak",0,null
  exec dbo.AddPerson "Józef","Huszczak",0,74
  exec dbo.AddPerson "W³adys³aw","Huszczak",1,80
  exec dbo.AddPerson "Leszek","Nowakowski",0,null
  exec dbo.AddPerson "W³adys³aw","Wójcik",0,78
  exec dbo.AddPerson "Krzysztof","Lewandowski",1,92
  exec dbo.AddPerson "Mateusz","Witek",1,74
  exec dbo.AddPerson "Krzysztof","Dudek",0,null
  exec dbo.AddPerson "Jan","B³aszczykowski",1,62
  exec dbo.AddPerson "Piotr","Kosowski",0,null
  exec dbo.AddPerson "Zbigniew","Nowak",0,35
  exec dbo.AddPerson "Jerzy","Filipowski",0,77
  exec dbo.AddPerson "Bartosz","B³aszczykowski",1,7
  exec dbo.AddPerson "Micha³","Frankowski",1,76
  exec dbo.AddPerson "Leszek","Wójcik",1,null
  exec dbo.AddPerson "Marek","Nowakowski",1,63
  exec dbo.AddPerson "Robert","Goleñ",1,96
  exec dbo.AddPerson "Józef","B³aszczykowski",0,null
  exec dbo.AddPerson "Jan","Huszczak",0,null
  exec dbo.AddPerson "Kacper","Goleñ",0,95
  exec dbo.AddPerson "Piotr","Kosowski",0,41
  exec dbo.AddPerson "Jerzy","Zaporowski",0,38
  exec dbo.AddPerson "Aberald","Wójcik",1,88
  exec dbo.AddPerson "Ryszard","Lewandowski",1,42
  exec dbo.AddPerson "Aberald","Nowak",1,null
  exec dbo.AddPerson "Piotr","Knapik",1,null
  exec dbo.AddPerson "Piotr","Wójcik",0,41
  exec dbo.AddPerson "Zbigniew","Huszczak",0,null
  exec dbo.AddPerson "Kacper","Wójcik",0,null
  exec dbo.AddPerson "Adam","B³aszczykowski",1,84
  exec dbo.AddPerson "Kamil","Kowalski",1,null
  exec dbo.AddPerson "Kamil","Nowakowski",1,100
  exec dbo.AddPerson "Robert","Frankowski",1,17
  exec dbo.AddPerson "Pawe³","Boruc",0,null
  exec dbo.AddPerson "Robert","Knapik",1,53
  exec dbo.AddPerson "Robert","Lewandowski",1,25
  exec dbo.AddPerson "Robert","B³aszczykowski",0,null
  exec dbo.AddPerson "Zbigniew","Kosowski",1,30
  exec dbo.AddPerson "Zbigniew","Witek",1,null
  exec dbo.AddPerson "Aberald","Knapik",1,72
  exec dbo.AddPerson "Adam","Nowak",0,12
  exec dbo.AddPerson "Józef","Dudek",1,null
  exec dbo.AddPerson "Ryszard","Nowakowski",0,38
  exec dbo.AddPerson "Kamil","Lewandowski",1,23
  exec dbo.AddPerson "Marek","Zaporowski",1,null
  exec dbo.AddPerson "Piotr","Witek",1,null
  exec dbo.AddPerson "Micha³","Lewandowski",1,null
  exec dbo.AddPerson "Pawe³","Zaporowski",1,null
  exec dbo.AddPerson "Bartosz","Kosowski",1,58
  exec dbo.AddPerson "Pawe³","B³aszczykowski",0,null
  exec dbo.AddPerson "Ryszard","Lewandowski",0,51
  exec dbo.AddPerson "Ryszard","Filipowski",1,62
  exec dbo.AddPerson "Zbigniew","Filipowski",1,10
  exec dbo.AddPerson "Mateusz","Wójcik",0,null
  exec dbo.AddPerson "Stanis³aw","B³aszczykowski",1,null
  exec dbo.AddPerson "Bartosz","Goleñ",0,null
  exec dbo.AddPerson "Kacper","Filipowski",1,14
  exec dbo.AddPerson "Kacper","Nowakowski",0,82
  exec dbo.AddPerson "Ryszard","Lewandowski",0,null
  exec dbo.AddPerson "Ryszard","Dudek",1,86
  exec dbo.AddPerson "Krzysztof","Giza",1,74
  exec dbo.AddPerson "W³adys³aw","Huszczak",1,76
  exec dbo.AddPerson "Józef","Goleñ",1,null
  exec dbo.AddPerson "Jan","Lewandowski",1,54
  exec dbo.AddPerson "Micha³","Goleñ",1,63
  exec dbo.AddPerson "Marek","Knapik",1,null
  exec dbo.AddPerson "Mateusz","Witek",0,20
  exec dbo.AddPerson "Micha³","Huszczak",0,null
  exec dbo.AddPerson "Bartosz","Nowak",0,64
  exec dbo.AddPerson "Józef","Lewandowski",0,null
  exec dbo.AddPerson "Kacper","Kowalski",1,null
  exec dbo.AddPerson "Jerzy","Giza",1,8
  exec dbo.AddPerson "W³adys³aw","Wójcik",1,47
  exec dbo.AddPerson "Mateusz","Huszczak",0,null
  exec dbo.AddPerson "Mateusz","Boruc",1,16
  exec dbo.AddPerson "Bartosz","Karasiñski",1,57
  exec dbo.AddPerson "W³adys³aw","Jankowski",0,null
  exec dbo.AddPerson "Stanis³aw","Kowalski",0,5
  exec dbo.AddPerson "Robert","Jankowski",1,12
  exec dbo.AddPerson "Piotr","Goleñ",0,27
  exec dbo.AddPerson "Mateusz","Goleñ",0,null
  exec dbo.AddPerson "Piotr","Knapik",0,29
  exec dbo.AddPerson "Robert","Lewandowski",0,12
  exec dbo.AddPerson "Józef","Piszczek",1,54
  exec dbo.AddPerson "Stanis³aw","Wójcik",1,null
  exec dbo.AddPerson "Ryszard","Jankowski",1,35
  exec dbo.AddPerson "Zbigniew","Knapik",0,17
  exec dbo.AddPerson "Robert","Karasiñski",1,null
  exec dbo.AddPerson "Leszek","Zaporowski",1,84
  exec dbo.AddPerson "Bartosz","Karasiñski",1,43
  exec dbo.AddPerson "Aberald","Kowalski",1,68
  exec dbo.AddPerson "Mateusz","Zaporowski",0,null
  exec dbo.AddPerson "Krzysztof","Lewandowski",1,null
  exec dbo.AddPerson "Krzysztof","Filipowski",0,null
  exec dbo.AddPerson "Aberald","Zaporowski",1,30
  exec dbo.AddPerson "W³adys³aw","Filipowski",0,52
  exec dbo.AddPerson "Pawe³","Witek",0,null
  exec dbo.AddPerson "Krzysztof","Karasiñski",1,null
  exec dbo.AddPerson "Aberald","Frankowski",1,null
  exec dbo.AddPerson "Józef","Piszczek",0,88
  exec dbo.AddPerson "Marek","Dudek",1,null
  exec dbo.AddPerson "Kamil","Wójcik",0,59
  exec dbo.AddPerson "Stanis³aw","Kowalski",0,65
  exec dbo.AddPerson "Bartosz","Huszczak",1,43
  exec dbo.AddPerson "Krzysztof","Karasiñski",1,null
  exec dbo.AddPerson "Mateusz","Piszczek",0,null
  exec dbo.AddPerson "Kamil","Karasiñski",1,null
  exec dbo.AddPerson "W³adys³aw","Filipowski",1,null
  exec dbo.AddPerson "Robert","Knapik",0,17
  exec dbo.AddPerson "Jerzy","Jankowski",1,15
  exec dbo.AddPerson "Bartosz","B³aszczykowski",0,5
  exec dbo.AddPerson "Aberald","Jankowski",1,null
  exec dbo.AddPerson "Piotr","Boruc",0,83
  exec dbo.AddPerson "Stanis³aw","Lewandowski",1,10
  exec dbo.AddPerson "Ryszard","Knapik",1,null
  exec dbo.AddPerson "Ryszard","Zaporowski",0,6
  exec dbo.AddPerson "Zbigniew","Lewandowski",1,9
  exec dbo.AddPerson "Zbigniew","Frankowski",1,null
  exec dbo.AddPerson "Robert","Nowakowski",0,86
  exec dbo.AddPerson "Stanis³aw","Wójcik",0,92
  exec dbo.AddPerson "Robert","Giza",1,59
  exec dbo.AddPerson "Kacper","Goleñ",1,38
  exec dbo.AddPerson "Kacper","B³aszczykowski",1,47
  exec dbo.AddPerson "Stanis³aw","Frankowski",1,null
  exec dbo.AddPerson "Aberald","Wójcik",0,null
  exec dbo.AddPerson "Jan","Jankowski",1,null
  exec dbo.AddPerson "Adam","Kowalski",0,91
  exec dbo.AddPerson "Kacper","Nowakowski",0,73
  exec dbo.AddPerson "Adam","B³aszczykowski",0,12
  exec dbo.AddPerson "Kamil","Lewandowski",1,83
  exec dbo.AddPerson "Adam","Dudek",1,49
  exec dbo.AddPerson "Robert","Boruc",1,41
  exec dbo.AddPerson "Jerzy","Zaporowski",0,null
  exec dbo.AddPerson "Leszek","Kosowski",1,null
  exec dbo.AddPerson "Marek","B³aszczykowski",0,59
  exec dbo.AddPerson "Józef","Jankowski",1,58
  exec dbo.AddPerson "Kacper","Piszczek",1,89
  exec dbo.AddPerson "Pawe³","Dudek",0,46
  exec dbo.AddPerson "Pawe³","Jankowski",1,null
  exec dbo.AddPerson "Józef","Piszczek",0,74
  exec dbo.AddPerson "Mateusz","Zaporowski",0,null
  exec dbo.AddPerson "Jerzy","Goleñ",0,46
  exec dbo.AddPerson "Micha³","Piszczek",0,53
  exec dbo.AddPerson "Mateusz","Kosowski",0,null
  exec dbo.AddPerson "Aberald","Zaporowski",0,null
  exec dbo.AddPerson "Stanis³aw","Knapik",0,null
  exec dbo.AddPerson "W³adys³aw","Karasiñski",0,38
  exec dbo.AddPerson "Marek","Wójcik",0,null
  exec dbo.AddPerson "Micha³","Boruc",1,null
  exec dbo.AddPerson "Józef","B³aszczykowski",0,19
  exec dbo.AddPerson "Robert","Kosowski",0,82
  exec dbo.AddPerson "Pawe³","Dudek",1,null
  exec dbo.AddPerson "Aberald","Goleñ",0,18
  exec dbo.AddPerson "Piotr","Giza",0,91
  exec dbo.AddPerson "Mateusz","Goleñ",1,null
  exec dbo.AddPerson "Krzysztof","Nowakowski",1,58
  exec dbo.AddPerson "Krzysztof","Filipowski",1,null
  exec dbo.AddPerson "Pawe³","Jankowski",1,88
  exec dbo.AddPerson "Kamil","Frankowski",0,100
  exec dbo.AddPerson "Józef","Karasiñski",1,null
  exec dbo.AddPerson "Ryszard","Lewandowski",1,73
  exec dbo.AddPerson "Piotr","Kosowski",1,61
  exec dbo.AddPerson "Kamil","Karasiñski",0,98
  exec dbo.AddPerson "Micha³","Huszczak",0,null
  exec dbo.AddPerson "Jan","Dudek",0,null
  exec dbo.AddPerson "Piotr","Knapik",0,null
  exec dbo.AddPerson "Robert","Goleñ",1,null
  exec dbo.AddPerson "Piotr","Witek",0,8
  exec dbo.AddPerson "Ryszard","Huszczak",0,null
  exec dbo.AddPerson "Piotr","Giza",1,89
  exec dbo.AddPerson "Krzysztof","Witek",0,null
  exec dbo.AddPerson "Marek","Kosowski",0,null
  exec dbo.AddPerson "Piotr","Wójcik",1,51
  exec dbo.AddPerson "Leszek","Filipowski",0,null
  exec dbo.AddPerson "Marek","Kosowski",0,92
  exec dbo.AddPerson "Jerzy","Knapik",0,null
  exec dbo.AddPerson "Kacper","Karasiñski",0,null
  exec dbo.AddPerson "Piotr","Jankowski",1,42
  exec dbo.AddPerson "Krzysztof","Wójcik",0,99
  exec dbo.AddPerson "Krzysztof","Piszczek",1,98
  exec dbo.AddPerson "Micha³","Frankowski",1,null
  exec dbo.AddPerson "Ryszard","Jankowski",0,49
  exec dbo.AddPerson "Bartosz","Nowakowski",1,null
  exec dbo.AddPerson "W³adys³aw","Nowak",0,4
  exec dbo.AddPerson "Kacper","Jankowski",1,null
  exec dbo.AddPerson "Jerzy","Goleñ",0,14
  exec dbo.AddPerson "Krzysztof","Karasiñski",1,80
  exec dbo.AddPerson "Aberald","Wójcik",1,null
  exec dbo.AddPerson "Zbigniew","Frankowski",1,null
  exec dbo.AddPerson "Kacper","Nowak",1,null
  exec dbo.AddPerson "Pawe³","Jankowski",0,null
  exec dbo.AddPerson "Micha³","Dudek",0,64
  exec dbo.AddPerson "Józef","Filipowski",0,null
  exec dbo.AddPerson "W³adys³aw","Huszczak",0,83
  exec dbo.AddPerson "Micha³","Kowalski",1,59
  exec dbo.AddPerson "Marek","Wójcik",0,null
  exec dbo.AddPerson "Piotr","Wójcik",1,null
  exec dbo.AddPerson "Kamil","B³aszczykowski",1,83
  exec dbo.AddPerson "Bartosz","Zaporowski",0,50
  exec dbo.AddPerson "Zbigniew","Filipowski",0,92
  exec dbo.AddPerson "Piotr","Piszczek",0,null
  exec dbo.AddPerson "Aberald","Goleñ",1,null
  exec dbo.AddPerson "Aberald","Karasiñski",0,null
  exec dbo.AddPerson "Mateusz","Goleñ",1,81
  exec dbo.AddPerson "Robert","Nowak",1,20
  exec dbo.AddPerson "Zbigniew","B³aszczykowski",1,null
  exec dbo.AddPerson "Piotr","Zaporowski",0,null
  exec dbo.AddPerson "W³adys³aw","Boruc",0,28
  exec dbo.AddPerson "Zbigniew","Nowakowski",1,null
  exec dbo.AddPerson "Jerzy","Goleñ",0,null
  exec dbo.AddPerson "Kamil","Giza",1,95
  exec dbo.AddPerson "Bartosz","Kowalski",1,78
  exec dbo.AddPerson "Bartosz","Witek",1,81
  exec dbo.AddPerson "Micha³","Lewandowski",0,null
  exec dbo.AddPerson "Stanis³aw","Piszczek",1,null
  exec dbo.AddPerson "Aberald","Nowakowski",1,null
  exec dbo.AddPerson "Aberald","Lewandowski",1,64
  exec dbo.AddPerson "Pawe³","Lewandowski",1,32
  exec dbo.AddPerson "Zbigniew","B³aszczykowski",0,null
  exec dbo.AddPerson "Ryszard","Nowakowski",1,86
  exec dbo.AddPerson "Marek","B³aszczykowski",0,null
  exec dbo.AddPerson "Kacper","Filipowski",1,82
  exec dbo.AddPerson "Robert","Lewandowski",0,65
  exec dbo.AddPerson "Robert","Filipowski",1,null
  exec dbo.AddPerson "Kacper","Huszczak",1,31
  exec dbo.AddPerson "Jan","Wójcik",0,37
  exec dbo.AddPerson "Jerzy","Witek",1,4
  exec dbo.AddPerson "Marek","Zaporowski",1,2
  exec dbo.AddPerson "Jan","B³aszczykowski",0,null
  exec dbo.AddPerson "Marek","B³aszczykowski",0,null
  exec dbo.AddPerson "Aberald","Huszczak",0,83
  exec dbo.AddPerson "Bartosz","Kowalski",1,null
  exec dbo.AddPerson "Kamil","Witek",1,null
  exec dbo.AddPerson "Kamil","Witek",0,85
  exec dbo.AddPerson "Micha³","Witek",0,65
  exec dbo.AddPerson "Mateusz","Knapik",0,7
  exec dbo.AddPerson "Leszek","Lewandowski",0,null
  exec dbo.AddPerson "Leszek","Filipowski",0,46
  exec dbo.AddPerson "Micha³","Frankowski",0,36
  exec dbo.AddPerson "Aberald","Frankowski",1,null
  exec dbo.AddPerson "Marek","B³aszczykowski",0,null
  exec dbo.AddPerson "Marek","Goleñ",1,60
  exec dbo.AddPerson "Pawe³","Nowakowski",1,47
  exec dbo.AddPerson "Adam","Karasiñski",1,null
  exec dbo.AddPerson "Jan","Filipowski",1,null
  exec dbo.AddPerson "Stanis³aw","Kosowski",0,null
  exec dbo.AddPerson "Józef","Giza",1,null
  exec dbo.AddPerson "Mateusz","Dudek",0,26
  exec dbo.AddPerson "Stanis³aw","Witek",0,65
  exec dbo.AddPerson "Jan","Nowak",0,null
  exec dbo.AddPerson "W³adys³aw","Knapik",0,42
  exec dbo.AddPerson "Leszek","Giza",1,22
  exec dbo.AddPerson "Zbigniew","Zaporowski",1,10
  exec dbo.AddPerson "Ryszard","Zaporowski",1,null
  exec dbo.AddPerson "Kacper","Nowakowski",1,null
  exec dbo.AddPerson "Piotr","Nowak",1,null
  exec dbo.AddPerson "W³adys³aw","Filipowski",0,28
  exec dbo.AddPerson "Adam","Filipowski",0,80
  exec dbo.AddPerson "Krzysztof","Wójcik",0,94
  exec dbo.AddPerson "W³adys³aw","Kosowski",0,17
  exec dbo.AddPerson "Kamil","Witek",1,60
  exec dbo.AddPerson "Pawe³","Huszczak",1,84
  exec dbo.AddPerson "Marek","Zaporowski",1,73
  exec dbo.AddPerson "Micha³","Filipowski",0,43
  exec dbo.AddPerson "Zbigniew","Karasiñski",1,null
  exec dbo.AddPerson "Ryszard","Jankowski",0,72
  exec dbo.AddPerson "Kacper","Giza",0,23
  exec dbo.AddPerson "Pawe³","Zaporowski",0,40
  exec dbo.AddPerson "Bartosz","Filipowski",1,null
  exec dbo.AddPerson "Jerzy","Piszczek",0,null
  exec dbo.AddPerson "Zbigniew","Boruc",1,null
  exec dbo.AddPerson "Józef","Frankowski",1,19
  exec dbo.AddPerson "Piotr","Boruc",1,69
  exec dbo.AddPerson "Robert","Kowalski",0,46
  exec dbo.AddPerson "Krzysztof","Knapik",0,15
  exec dbo.AddPerson "Stanis³aw","B³aszczykowski",1,null
  exec dbo.AddPerson "Robert","Kosowski",1,null
  exec dbo.AddPerson "Józef","Lewandowski",1,null
  exec dbo.AddPerson "Jan","Nowak",0,null
  exec dbo.AddPerson "Jerzy","Knapik",0,38
  exec dbo.AddPerson "Piotr","Huszczak",1,null
  exec dbo.AddPerson "Aberald","Goleñ",0,99
  exec dbo.AddPerson "Pawe³","Dudek",0,null
  exec dbo.AddPerson "Józef","Filipowski",1,null
  exec dbo.AddPerson "Leszek","Frankowski",1,null
  exec dbo.AddPerson "W³adys³aw","Witek",0,90
  exec dbo.AddPerson "Adam","Zaporowski",0,7
  exec dbo.AddPerson "Mateusz","Filipowski",1,100
  exec dbo.AddPerson "Micha³","B³aszczykowski",1,14
  exec dbo.AddPerson "Adam","Giza",1,28
  exec dbo.AddPerson "Aberald","Huszczak",0,null
  exec dbo.AddPerson "Jerzy","Piszczek",1,null
  exec dbo.AddPerson "Piotr","Karasiñski",0,38
  exec dbo.AddPerson "Robert","Zaporowski",1,13
  exec dbo.AddPerson "Ryszard","Nowakowski",0,11
  exec dbo.AddPerson "Krzysztof","Nowak",1,96
  exec dbo.AddPerson "Jerzy","Jankowski",1,null
  exec dbo.AddPerson "Leszek","Boruc",1,null
  exec dbo.AddPerson "Kacper","Karasiñski",1,71
  exec dbo.AddPerson "Jan","Knapik",1,null
  exec dbo.AddPerson "Micha³","Piszczek",0,57
  exec dbo.AddPerson "Leszek","Boruc",0,null
  exec dbo.AddPerson "Kamil","Knapik",0,null
  exec dbo.AddPerson "Kamil","Wójcik",1,null
  exec dbo.AddPerson "Marek","Kowalski",0,14
  exec dbo.AddPerson "Mateusz","B³aszczykowski",1,97
  exec dbo.AddPerson "Bartosz","Kowalski",0,97
  exec dbo.AddPerson "Bartosz","Nowakowski",0,null
  exec dbo.AddPerson "Jan","Knapik",0,98
  exec dbo.AddPerson "Leszek","Witek",0,2
  exec dbo.AddPerson "Adam","Dudek",1,null
  exec dbo.AddPerson "Mateusz","Karasiñski",1,81
  exec dbo.AddPerson "Zbigniew","Lewandowski",0,null
  exec dbo.AddPerson "Kacper","Goleñ",0,null
  exec dbo.AddPerson "Ryszard","Knapik",1,87
  exec dbo.AddPerson "Micha³","Giza",0,null
  exec dbo.AddPerson "Ryszard","Filipowski",1,null
  exec dbo.AddPerson "Aberald","Goleñ",0,null
  exec dbo.AddPerson "Robert","Filipowski",0,72