USE [u_jastrzab]
GO
  exec dbo.AddAddress "Œwierkowa","15-125","Limanowa","Polska"
  exec dbo.AddAddress "Kopernika","52-857","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Kopernika","31-512","Gorzów Wielkopolski","Polska"
  exec dbo.AddAddress "Konopnickiej","41-125","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Sezamkowa","15-125","Œwinoujœcie","Polska"
  exec dbo.AddAddress "Grzybowa","43-300","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "S³oneczna","15-125","Bia³ystok","Polska"
  exec dbo.AddAddress "Kopernika","34-243","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Macierzanki","23-671","Gdañsk","Polska"
  exec dbo.AddAddress "Mickiewicza","40-127","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Tetmajera","12-621","Œwinoujœcie","Polska"
  exec dbo.AddAddress "Kijowska","52-857","Gorzów Wielkopolski","Polska"
  exec dbo.AddAddress "Biernackiego","23-671","Kasina Wielka","Polska"
  exec dbo.AddAddress "Piastowska","40-127","Gdañsk","Polska"
  exec dbo.AddAddress "Sezamkowa","22-123","Bia³ystok","Polska"
  exec dbo.AddAddress "Mickiewicza","76-243","Gdów","Polska"
  exec dbo.AddAddress "Kopernika","30-213","Toruñ","Polska"
  exec dbo.AddAddress "Kopernika","34-243","Kasina Wielka","Polska"
  exec dbo.AddAddress "Krakowska","40-127","Œwinoujœcie","Polska"
  exec dbo.AddAddress "S³owackiego","23-671","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Tetmajera","30-213","Ciechocinek","Polska"
  exec dbo.AddAddress "Warszawska","40-127","Toruñ","Polska"
  exec dbo.AddAddress "Doro¿karzy","41-125","Bia³ystok","Polska"
  exec dbo.AddAddress "Mickiewicza","32-132","Toruñ","Polska"
  exec dbo.AddAddress "Brzozowa","15-125","Gdañsk","Polska"
  exec dbo.AddAddress "S³owackiego","15-125","Œwinoujœcie","Polska"
  exec dbo.AddAddress "S³oneczna","15-231","Lublin","Polska"
  exec dbo.AddAddress "Olszowska","43-344","Gdañsk","Polska"
  exec dbo.AddAddress "Olszowska","15-231","Ciechocinek","Polska"
  exec dbo.AddAddress "Krakowska","43-344","Kasina Wielka","Polska"
  exec dbo.AddAddress "Brzozowa","41-125","Kraków","Polska"
  exec dbo.AddAddress "Grzybowa","43-300","Kraków","Polska"
  exec dbo.AddAddress "Wiedeñska","12-732","Warszawa","Polska"
  exec dbo.AddAddress "Tetmajera","22-123","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Kryszta³owa","15-231","Limanowa","Polska"
  exec dbo.AddAddress "Mickiewicza","12-121","Gdynia","Polska"
  exec dbo.AddAddress "Mickiewicza","15-231","Lublin","Polska"
  exec dbo.AddAddress "Doro¿karzy","12-121","Szczecin","Polska"
  exec dbo.AddAddress "Brzozowa","76-243","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Kijowska","12-521","Œwinoujœcie","Polska"
  exec dbo.AddAddress "Warszawska","76-243","Ruciane-Nida","Polska"
  exec dbo.AddAddress "Konopnickiej","12-521","Kasina Wielka","Polska"
  exec dbo.AddAddress "Doro¿karzy","12-621","Limanowa","Polska"
  exec dbo.AddAddress "Piastowska","31-512","Gdynia","Polska"
  exec dbo.AddAddress "Piastowska","12-521","Wadowice","Polska"
  exec dbo.AddAddress "S³oneczna","43-344","Warszawa","Polska"
  exec dbo.AddAddress "Kijowska","12-732","Œwinoujœcie","Polska"
  exec dbo.AddAddress "S³oneczna","12-732","Ciechocinek","Polska"
  exec dbo.AddAddress "Konopnickiej","43-344","Kraków","Polska"
  exec dbo.AddAddress "Biernackiego","11-732","Gdañsk","Polska"
  exec dbo.AddAddress "Wiedeñska","23-671","Gorzów Wielkopolski","Polska"
  exec dbo.AddAddress "Konopnickiej","15-231","Gdañsk","Polska"
  exec dbo.AddAddress "Biernackiego","15-125","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Œwierkowa","12-621","Wadowice","Polska"
  exec dbo.AddAddress "Konopnickiej","12-521","Gdynia","Polska"
  exec dbo.AddAddress "Kopernika","12-121","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Olszowska","40-127","Gdynia","Polska"
  exec dbo.AddAddress "Brzozowa","43-344","Kraków","Polska"
  exec dbo.AddAddress "Kryszta³owa","12-121","Gorzów Wielkopolski","Polska"
  exec dbo.AddAddress "Doro¿karzy","15-231","Œwinoujœcie","Polska"
  exec dbo.AddAddress "Biernackiego","22-122","Poznañ","Polska"
  exec dbo.AddAddress "Biernackiego","12-121","Ruciane-Nida","Polska"
  exec dbo.AddAddress "Kryszta³owa","34-243","Gdów","Polska"
  exec dbo.AddAddress "Sezamkowa","40-127","Warszawa","Polska"
  exec dbo.AddAddress "Kryszta³owa","12-521","Ruciane-Nida","Polska"
  exec dbo.AddAddress "Konopnickiej","11-732","Lublin","Polska"
  exec dbo.AddAddress "Sezamkowa","76-243","Gdañsk","Polska"
  exec dbo.AddAddress "Grzybowa","40-127","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Mickiewicza","34-243","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Kryszta³owa","22-122","Lublin","Polska"
  exec dbo.AddAddress "Grzybowa","12-121","Gdów","Polska"
  exec dbo.AddAddress "Piastowska","11-732","Kasina Wielka","Polska"
  exec dbo.AddAddress "Tetmajera","15-231","Toruñ","Polska"
  exec dbo.AddAddress "Brzozowa","41-125","Rzeszów","Polska"
  exec dbo.AddAddress "S³owackiego","22-123","Limanowa","Polska"
  exec dbo.AddAddress "Warszawska","12-732","Warszawa","Polska"
  exec dbo.AddAddress "Wiedeñska","22-123","Gdynia","Polska"
  exec dbo.AddAddress "Krakowska","34-243","Gdañsk","Polska"
  exec dbo.AddAddress "Kryszta³owa","23-671","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Wiedeñska","30-213","Ciechocinek","Polska"
  exec dbo.AddAddress "Brzozowa","15-125","Kasina Wielka","Polska"
  exec dbo.AddAddress "Sezamkowa","15-125","Limanowa","Polska"
  exec dbo.AddAddress "Piastowska","32-132","Ciechocinek","Polska"
  exec dbo.AddAddress "Biernackiego","43-300","Gorzów Wielkopolski","Polska"
  exec dbo.AddAddress "Wiedeñska","52-857","Kasina Wielka","Polska"
  exec dbo.AddAddress "S³oneczna","12-521","Toruñ","Polska"
  exec dbo.AddAddress "Kopernika","34-243","Ciechocinek","Polska"
  exec dbo.AddAddress "Warszawska","31-512","Limanowa","Polska"
  exec dbo.AddAddress "Krakowska","12-621","Ruciane-Nida","Polska"
  exec dbo.AddAddress "Krakowska","12-521","Œwinoujœcie","Polska"
  exec dbo.AddAddress "Olszowska","11-732","Limanowa","Polska"
  exec dbo.AddAddress "Kijowska","12-121","Limanowa","Polska"
  exec dbo.AddAddress "Krakowska","11-732","Warszawa","Polska"
  exec dbo.AddAddress "Biernackiego","11-732","Kasina Wielka","Polska"
  exec dbo.AddAddress "S³owackiego","12-521","Bielsko-Bia³a","Polska"
  exec dbo.AddAddress "Konopnickiej","12-521","Rzeszów","Polska"
  exec dbo.AddAddress "Mickiewicza","15-231","Kasina Wielka","Polska"
  exec dbo.AddAddress "Wiedeñska","12-732","Bia³ystok","Polska"
  exec dbo.AddAddress "Doro¿karzy","34-243","Ko³obrzeg","Polska"
  exec dbo.AddAddress "Œwierkowa","43-300","Ruciane-Nida","Polska"